set_attack_value(AT_EXTRA_3, AG_CATEGORY, 2);
set_attack_value(AT_EXTRA_3, AG_SPRITE, sprite_get("EXTRA_3"));
set_attack_value(AT_EXTRA_3, AG_NUM_WINDOWS, 3);
set_attack_value(AT_EXTRA_3, AG_HURTBOX_SPRITE, sprite_get("EXTRA_3_hurt"));

set_window_value(AT_EXTRA_3, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_LENGTH, 20);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_ANIM_FRAME_START, 12);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_SFX, sound_get("whistle"));

set_num_hitboxes(AT_EXTRA_3, 1);

// CANNONBALL GOING FORWARD
set_hitbox_value(AT_EXTRA_3, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_3, 1, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_LIFETIME, 999);
set_hitbox_value(AT_EXTRA_3, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_WIDTH, 32);
set_hitbox_value(AT_EXTRA_3, 1, HG_HEIGHT, 32);
set_hitbox_value(AT_EXTRA_3, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_3, 1, HG_DAMAGE, 6);
set_hitbox_value(AT_EXTRA_3, 1, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_3, 1, HG_KNOCKBACK_SCALING, .6);
set_hitbox_value(AT_EXTRA_3, 1, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_3, 1, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_SPRITE, sprite_get("extra_3_proj"));
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_MASK, sprite_get("extra_3_proj"));
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_VISUAL_EFFECT, 153);
set_hitbox_value(AT_EXTRA_3, 1, HG_VISUAL_EFFECT_Y_OFFSET, 32);
set_hitbox_value(AT_EXTRA_3, 1, HG_HIT_SFX, asset_get("sfx_metal_hit_strong"));
set_hitbox_value(AT_EXTRA_3, 1, HG_ANGLE_FLIPPER, 3);

// CANNONBALL GOING UP
set_hitbox_value(AT_EXTRA_3, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_EXTRA_3, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_3, 3, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_3, 3, HG_LIFETIME, 999);
set_hitbox_value(AT_EXTRA_3, 3, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_WIDTH, 32);
set_hitbox_value(AT_EXTRA_3, 3, HG_HEIGHT, 32);
set_hitbox_value(AT_EXTRA_3, 3, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_3, 3, HG_DAMAGE, 6);
set_hitbox_value(AT_EXTRA_3, 3, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_3, 3, HG_KNOCKBACK_SCALING, .6);
set_hitbox_value(AT_EXTRA_3, 3, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_3, 3, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_SPRITE, sprite_get("extra_3_proj"));
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_MASK, sprite_get("extra_3_proj"));
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_VSPEED, -5);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 3, HG_VISUAL_EFFECT, 153);
set_hitbox_value(AT_EXTRA_3, 3, HG_VISUAL_EFFECT_Y_OFFSET, 32);
set_hitbox_value(AT_EXTRA_3, 3, HG_HIT_SFX, asset_get("sfx_metal_hit_strong"));
set_hitbox_value(AT_EXTRA_3, 3, HG_ANGLE_FLIPPER, 3);

// CANNONBALL GOING DIAG FORWARD
set_hitbox_value(AT_EXTRA_3, 4, HG_PARENT_HITBOX, 4);
set_hitbox_value(AT_EXTRA_3, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_3, 4, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_3, 4, HG_LIFETIME, 999);
set_hitbox_value(AT_EXTRA_3, 4, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_3, 4, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_3, 4, HG_WIDTH, 32);
set_hitbox_value(AT_EXTRA_3, 4, HG_HEIGHT, 32);
set_hitbox_value(AT_EXTRA_3, 4, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_3, 4, HG_DAMAGE, 6);
set_hitbox_value(AT_EXTRA_3, 4, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_3, 4, HG_KNOCKBACK_SCALING, .6);
set_hitbox_value(AT_EXTRA_3, 4, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_3, 4, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_SPRITE, sprite_get("extra_3_proj"));
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_MASK, sprite_get("extra_3_proj"));
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_VSPEED, -4);
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_HSPEED, 4);
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 4, HG_VISUAL_EFFECT, 153);
set_hitbox_value(AT_EXTRA_3, 4, HG_VISUAL_EFFECT_Y_OFFSET, 32);
set_hitbox_value(AT_EXTRA_3, 4, HG_HIT_SFX, asset_get("sfx_metal_hit_strong"));
set_hitbox_value(AT_EXTRA_3, 4, HG_ANGLE_FLIPPER, 3);

// CANNONBALL GOING BACKWARDS
set_hitbox_value(AT_EXTRA_3, 9, HG_PARENT_HITBOX, 9);
set_hitbox_value(AT_EXTRA_3, 9, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_3, 9, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_3, 9, HG_LIFETIME, 999);
set_hitbox_value(AT_EXTRA_3, 9, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_3, 9, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_3, 9, HG_WIDTH, 32);
set_hitbox_value(AT_EXTRA_3, 9, HG_HEIGHT, 32);
set_hitbox_value(AT_EXTRA_3, 9, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_3, 9, HG_DAMAGE, 6);
set_hitbox_value(AT_EXTRA_3, 9, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_3, 9, HG_KNOCKBACK_SCALING, .6);
set_hitbox_value(AT_EXTRA_3, 9, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_3, 9, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXTRA_3, 9, HG_PROJECTILE_SPRITE, sprite_get("extra_3_proj"));
set_hitbox_value(AT_EXTRA_3, 9, HG_PROJECTILE_MASK, sprite_get("extra_3_proj"));
set_hitbox_value(AT_EXTRA_3, 9, HG_PROJECTILE_HSPEED, -5);
set_hitbox_value(AT_EXTRA_3, 9, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 9, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 9, HG_VISUAL_EFFECT, 153);
set_hitbox_value(AT_EXTRA_3, 9, HG_VISUAL_EFFECT_Y_OFFSET, 32);
set_hitbox_value(AT_EXTRA_3, 9, HG_HIT_SFX, asset_get("sfx_metal_hit_strong"));
set_hitbox_value(AT_EXTRA_3, 9, HG_ANGLE_FLIPPER, 3);

// CANNONBALL GOING DIAG BACKWARDS
set_hitbox_value(AT_EXTRA_3, 10, HG_PARENT_HITBOX, 10);
set_hitbox_value(AT_EXTRA_3, 10, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_3, 10, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_3, 10, HG_LIFETIME, 999);
set_hitbox_value(AT_EXTRA_3, 10, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_3, 10, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_3, 10, HG_WIDTH, 32);
set_hitbox_value(AT_EXTRA_3, 10, HG_HEIGHT, 32);
set_hitbox_value(AT_EXTRA_3, 10, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_3, 10, HG_DAMAGE, 6);
set_hitbox_value(AT_EXTRA_3, 10, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_3, 10, HG_KNOCKBACK_SCALING, .6);
set_hitbox_value(AT_EXTRA_3, 10, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_3, 10, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXTRA_3, 10, HG_PROJECTILE_SPRITE, sprite_get("extra_3_proj"));
set_hitbox_value(AT_EXTRA_3, 10, HG_PROJECTILE_MASK, sprite_get("extra_3_proj"));
set_hitbox_value(AT_EXTRA_3, 10, HG_PROJECTILE_VSPEED, -4);
set_hitbox_value(AT_EXTRA_3, 10, HG_PROJECTILE_HSPEED, -4);
set_hitbox_value(AT_EXTRA_3, 10, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 10, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 10, HG_VISUAL_EFFECT, 153);
set_hitbox_value(AT_EXTRA_3, 10, HG_VISUAL_EFFECT_Y_OFFSET, 32);
set_hitbox_value(AT_EXTRA_3, 10, HG_HIT_SFX, asset_get("sfx_metal_hit_strong"));
set_hitbox_value(AT_EXTRA_3, 10, HG_ANGLE_FLIPPER, 3);
