set_attack_value(AT_EXTRA_2, AG_CATEGORY, 2);
set_attack_value(AT_EXTRA_2, AG_SPRITE, sprite_get("EXTRA_2"));
set_attack_value(AT_EXTRA_2, AG_NUM_WINDOWS, 3);
set_attack_value(AT_EXTRA_2, AG_HURTBOX_SPRITE, sprite_get("EXTRA_2_hurt"));

set_window_value(AT_EXTRA_2, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_LENGTH, 20);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_ANIM_FRAME_START, 12);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_SFX, sound_get("whistle"));

set_num_hitboxes(AT_EXTRA_2, 6);

// FIRE BAR FIREBALL HITBOXES

set_hitbox_value(AT_EXTRA_2, 1, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 1, HG_LIFETIME, 999);
set_hitbox_value(AT_EXTRA_2, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_SPRITE, sprite_get("fireball"));
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_MASK, sprite_get("fireball"));
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_2, 1, HG_VISUAL_EFFECT, 3);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_DESTROY_EFFECT, 3);
set_hitbox_value(AT_EXTRA_2, 1, HG_HIT_SFX, sound_get("podoboo"));

set_hitbox_value(AT_EXTRA_2, 2, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_LIFETIME, 999);
set_hitbox_value(AT_EXTRA_2, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_SPRITE, sprite_get("fireball"));
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_MASK, sprite_get("fireball"));
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_2, 2, HG_VISUAL_EFFECT, 3);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_DESTROY_EFFECT, 3);
set_hitbox_value(AT_EXTRA_2, 2, HG_HIT_SFX, sound_get("podoboo"));

set_hitbox_value(AT_EXTRA_2, 3, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 3, HG_LIFETIME, 999);
set_hitbox_value(AT_EXTRA_2, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_SPRITE, sprite_get("fireball"));
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_MASK, sprite_get("fireball"));
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_2, 3, HG_VISUAL_EFFECT, 3);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_DESTROY_EFFECT, 3);
set_hitbox_value(AT_EXTRA_2, 3, HG_HIT_SFX, sound_get("podoboo"));

set_hitbox_value(AT_EXTRA_2, 4, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 4, HG_LIFETIME, 999);
set_hitbox_value(AT_EXTRA_2, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_SPRITE, sprite_get("fireball"));
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_MASK, sprite_get("fireball"));
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_2, 4, HG_VISUAL_EFFECT, 3);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_DESTROY_EFFECT, 3);
set_hitbox_value(AT_EXTRA_2, 4, HG_HIT_SFX, sound_get("podoboo"));

set_hitbox_value(AT_EXTRA_2, 5, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_EXTRA_2, 5, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 5, HG_LIFETIME, 999);
set_hitbox_value(AT_EXTRA_2, 5, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_SPRITE, sprite_get("fireball"));
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_MASK, sprite_get("fireball"));
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_2, 5, HG_VISUAL_EFFECT, 3);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_DESTROY_EFFECT, 3);
set_hitbox_value(AT_EXTRA_2, 5, HG_HIT_SFX, sound_get("podoboo"));

set_hitbox_value(AT_EXTRA_2, 6, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_EXTRA_2, 6, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 6, HG_LIFETIME, 999);
set_hitbox_value(AT_EXTRA_2, 6, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 6, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 6, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_2, 6, HG_PROJECTILE_SPRITE, sprite_get("fireball"));
set_hitbox_value(AT_EXTRA_2, 6, HG_PROJECTILE_MASK, sprite_get("fireball"));
set_hitbox_value(AT_EXTRA_2, 6, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_EXTRA_2, 6, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 6, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 6, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_2, 6, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_2, 6, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_2, 6, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_2, 6, HG_VISUAL_EFFECT, 3);
set_hitbox_value(AT_EXTRA_2, 6, HG_PROJECTILE_DESTROY_EFFECT, 3);
set_hitbox_value(AT_EXTRA_2, 6, HG_HIT_SFX, sound_get("podoboo"));
