set_attack_value(AT_NSPECIAL_2, AG_CATEGORY, 2);
set_attack_value(AT_NSPECIAL_2, AG_SPRITE, sprite_get("nspecial"));
set_attack_value(AT_NSPECIAL_2, AG_NUM_WINDOWS, 3);
set_attack_value(AT_NSPECIAL_2, AG_HURTBOX_SPRITE, sprite_get("nspecial_hurt"));

set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_LENGTH, 20);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_ANIM_FRAME_START, 11);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_SFX, sound_get("whistle"));
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_HSPEED_TYPE, 1);

set_window_value(AT_NSPECIAL_2, 2, AG_WINDOW_LENGTH, 24);
set_window_value(AT_NSPECIAL_2, 2, AG_WINDOW_ANIM_FRAMES, 8);
set_window_value(AT_NSPECIAL_2, 2, AG_WINDOW_ANIM_FRAME_START, 15);
set_window_value(AT_NSPECIAL_2, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NSPECIAL_2, 2, AG_WINDOW_SFX, sound_get("thunder"));
set_window_value(AT_NSPECIAL_2, 2, AG_WINDOW_HAS_WHIFFLAG, 1);
set_window_value(AT_NSPECIAL_2, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_NSPECIAL_2, 2, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_NSPECIAL_2, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_NSPECIAL_2, 2, AG_WINDOW_HSPEED_TYPE, 1);

set_window_value(AT_NSPECIAL_2, 3, AG_WINDOW_LENGTH, 9);
set_window_value(AT_NSPECIAL_2, 3, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_NSPECIAL_2, 3, AG_WINDOW_ANIM_FRAME_START, 23);

set_window_value(AT_NSPECIAL_2, 4, AG_WINDOW_TYPE, 7);
set_window_value(AT_NSPECIAL_2, 4, AG_WINDOW_LENGTH, 9);
set_window_value(AT_NSPECIAL_2, 4, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_NSPECIAL_2, 4, AG_WINDOW_ANIM_FRAME_START, 23);

set_num_hitboxes(AT_NSPECIAL_2, 3);

set_hitbox_value(AT_NSPECIAL_2, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_WINDOW, 2);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_LIFETIME, 5);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HITBOX_Y, -36);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_WIDTH, 80);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HEIGHT, 80);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_DAMAGE, 35);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_ANGLE, 75);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_EFFECT, 1);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_BASE_KNOCKBACK, 15);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_KNOCKBACK_SCALING, 1.0);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HITPAUSE_SCALING, .6);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_VISUAL_EFFECT, 141);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HIT_SFX, asset_get("sfx_ori_energyhit_heavy"));
set_hitbox_value(AT_NSPECIAL_2, 1, HG_EXTRA_CAMERA_SHAKE, 1);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_TECHABLE, 3);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_ANGLE_FLIPPER, 3);

set_hitbox_value(AT_NSPECIAL_2, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_WINDOW, 2);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_LIFETIME, 10);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HITBOX_Y, -36);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_WIDTH, 132);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HEIGHT, 132);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_DAMAGE, 15);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_ANGLE, 50);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_EFFECT, 1);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_KNOCKBACK_SCALING, .9);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_FINAL_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_VISUAL_EFFECT, 141);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HIT_SFX, asset_get("sfx_ori_energyhit_weak"));
set_hitbox_value(AT_NSPECIAL_2, 2, HG_ANGLE_FLIPPER, 3);

set_hitbox_value(AT_NSPECIAL_2, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_WINDOW, 2);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_WINDOW_CREATION_FRAME, 10);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_LIFETIME, 15);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HITBOX_Y, -36);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_WIDTH, 190);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HEIGHT, 190);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_DAMAGE, 5);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_EFFECT, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_VISUAL_EFFECT, 13);